### Fatoração de matrizes

Objetivo: explorar  como  as ferramentas de Álgebra Linear podem desvendar as informações ocultas nas interações dos   usuários   com   sistemas   de   recomendação.

Nos sistemas de recomendação, frequentemente utilizamos a **matriz de avaliações** ou **matrizes de interações** para representar as interações dos usuários com os itens. A matriz é composta por linhas (usuários) e colunas (itens), e suas células contêm as avaliações dos usuários para os itens. 

No entanto, essas matrizes costumam ser esparsas, ou seja, **muitos valores estão vazios porque nem todos os usuários avaliam todos os itens**. A partir dessa matriz, as técnicas matemáticas são aplicadas para encontrar padrões e realizar as recomendações.


**Recomendação por similaridade (seja por perfis de pessoas ou por vizinhança)**

Os vetores de correlação e similaridade são estruturas fundamentais para capturar as preferências em matrizes de recomendação. Calcular essas métricas entre os vetores de interação de diferentes usuários possibilitam a identificação de comportamento similares.

Ao aplicar essas métricas, sistemas de recomendação podem agrupar usuários com gostos semelhantes e sugerir itens que foram bem avaliados por um usuário a outro com perfil similar.

## Introdução

In [1]:
#Observe o código-fonte a seguir, que traz um exemplo de operações matriciais com Python e Numpy:

import numpy as np

# Definindo duas matrizes
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# Multiplicando as matrizes
C = np.dot(A, B)
print("Resultado da Multiplicação de Matrizes:\n", C)

Resultado da Multiplicação de Matrizes:
 [[ 4  4]
 [10  8]]


In [4]:
#Prosseguiremos  com  a  Fatoração  de  Matrizes  Não-Negativas,  
# um  método poderoso para decompor uma matriz em componentes que capturam 
# a estrutura dos dados de maneira eficiente e intuitiva:

from sklearn.decomposition import NMF

# Dados exemplo
V = np.array([[1, 2], [3, 4], [5, 6]])
model = NMF(n_components=1, init='random', random_state=0)
W = model.fit_transform(V)
H = model.components_
print("Matriz W (Base):\n", W)
print("Matriz H (Coeficientes):\n", H)

Matriz W (Base):
 [[0.50424333]
 [1.15119452]
 [1.79814571]]
Matriz H (Coeficientes):
 [[2.69041988 3.40799721]]


In [20]:
#Vamos explorar os mecanismos de exploração e explotação através de  exemplos  de  código  em  Python
import numpy as np
import random

# Definindo um simples conjunto de recomendações
recomendacoes  =  [1,  2,  3,  4,  5]    #  Representa  ids  de  itens recomendáveis
epsilon = 0.1  # 10% de chance de explorar

# Escolha entre explorar ou explotar
if random.random() < epsilon:
    # Explorar: escolher um item aleatório
    item_recomendado = random.choice(recomendacoes)
else:
    # Explotar: escolher o melhor item, assumindo que o item 5 é o melhor
    item_recomendado = 5
print("Item Recomendado:", item_recomendado)

Item Recomendado: 5


## Fundamentos

Exploraremos os fundamentos matemáticos e estatísticos que sustentam os algoritmos de recomendação. Iremos discutir como diferentes métodos de fatoração, como SVD (Decomposição em Valores Singulares) e NMF (Fatoração de Matrizes Não-Negativas), são aplicados para descobrir padrões latentes  em  grandes  conjuntos  de  dados,  facilitando  assim  recomendações  mais precisas e personalizadas.

**Álgebra  linear**  é  um  ramo  fundamental  da  matemática  que  trata  de  vetores, espaços  vetoriais  (também  conhecidos  como  espaços  lineares),  transformações lineares e sistemas de equações lineares. Em particular, as matrizes, que são arranjos retangulares  de  números,  desempenham  um  papel  central  na  álgebra  linear,  pois facilitam a manipulação de grandes conjuntos de equações lineares. 

Uma matriz é definida por suas linhas (horizontais) e colunas (verticais), cada entrada  na  matriz  sendo  um  elemento que pode  ser  um  número  real  ou  complexo. Formalmente, Uma matriz é uma representação retangular de elementos arranjados em linhas e colunas.Assim, uma matriz A de dimensão mxn sobre o conjunto dos números reais ℝé uma coleção ordenada de números reais dispostos em m linhas e n colunas. 

### Autovalores e Autovetores

Autovalores e autovetores são conceitos fundamentais em álgebra linear e desempenham um papel importante em várias áreas da matemática e da computação, incluindo sistemas de recomendação e análise de dados.

De forma simplificada, autovalores e autovetores surgem quando queremos entender as propriedades de uma matriz. Quando aplicamos uma transformação (como uma multiplicação) a um vetor (um conjunto de números), o vetor geralmente muda — ele pode ser esticado, encolhido, ou até rotacionado. Porém, há casos em que a transformação não muda a direção do vetor, apenas seu comprimento. Esses vetores, que não mudam de direção após a transformação, são chamados de autovetores. E o fator pelo qual o vetor é esticado ou encolhido é chamado de autovalor.

Seja uma matriz 𝐴 e um vetor 𝑣, a multiplicação da matriz pelo vetor pode ser representada como:
𝐴⋅𝑣=𝜆⋅𝑣

Onde:

* 𝐴 é a matriz de transformação.
* 𝑣 é o autovetor.
* 𝜆 é o autovalor.

A ideia é que, quando multiplicamos a matriz 𝐴 pelo vetor 𝑣, o vetor 𝑣 não muda de direção — ele apenas é esticado ou encolhido pela constante 𝜆 (o autovalor).

Um exemplo prático de onde autovalores e autovetores são usados é na redução de dimensionalidade em sistemas de recomendação, como no SVD (Decomposição em Valores Singulares). Quando se tem uma grande matriz de interações de usuários com itens, pode ser difícil encontrar padrões diretamente devido à grande quantidade de dados. Uma maneira de resolver isso é decompor a matriz em componentes menores, representados por autovetores e autovalores. Esses componentes podem revelar as dimensões latentes dos dados, ou seja, as características subjacentes que não são diretamente visíveis, mas que são importantes para entender as preferências dos usuários ou as características dos itens.

Por exemplo, no caso de filmes, um autovetor pode representar uma característica latente, como o "gênero do filme", e o autovalor correspondente pode indicar a força dessa característica (quanto ela influencia na preferência do usuário). A decomposição em autovalores e autovetores ajuda a reduzir a dimensionalidade dos dados, tornando os cálculos mais eficientes e revelando padrões que poderiam ser difíceis de identificar em uma grande matriz cheia de dados.

### Diagonalização da matriz

Diagonalização de matriz é um processo que envolve transformar uma matriz quadrada 𝐴 em uma matriz diagonal 𝐷 que é similar à matriz original. Esse processo é útil porque as matrizes diagonais são muito mais fáceis de lidar, especialmente quando se trata de calcular potências de matrizes ou de realizar decomposições, o que pode ser essencial em várias aplicações, como na resolução de sistemas diferenciais, na análise de sistemas dinâmicos e em algoritmos de aprendizado de máquina.

O que é a diagonalização?

Para entender a diagonalização, primeiro é importante saber que uma matriz diagonal é uma matriz em que todos os elementos fora da diagonal principal (a linha que vai do canto superior esquerdo ao canto inferior direito) são zero.

A diagonalização de uma matriz 𝐴 consiste em encontrar uma matriz invertível 𝑃 e uma matriz diagonal 𝐷 tal que:
𝐴=𝑃⋅𝐷⋅𝑃^(−1)

Aqui, 𝑃 é uma matriz cujas colunas são os autovetores de A, e 𝐷 é a matriz diagonal cujos elementos são os autovalores de 𝐴.

Como funciona?

A ideia principal da diagonalização é que uma matriz 𝐴 pode ser "quase transformada" em uma matriz diagonal 𝐷 se houver um conjunto suficiente de autovetores e autovalores associados a ela.

Quando uma matriz é diagonalizável?

Nem todas as matrizes podem ser diagonalizadas. Para uma matriz 𝐴 ser diagonalizável, ela precisa satisfazer as seguintes condições:

* Número suficiente de autovetores linearmente independentes: A matriz precisa ter 𝑛 autovetores linearmente independentes, onde 𝑛 é o número de linhas (ou colunas) da matriz. Isso garante que a matriz 𝑃, formada pelos autovetores, seja invertível.
* Autovalores distintos (em muitos casos): Se a matriz tem autovalores distintos, ela pode ser diagonalizada facilmente. No entanto, até mesmo matrizes com autovalores repetidos podem ser diagonalizadas, desde que ainda possuam o número adequado de autovetores linearmente independentes.

## Aprofundamento

* "Breve  introdução  à Álgebra Linear" e "Espaços latentes" podem ser explorados detalhadamente no livro de   John   A.   Lee   e   Michel   Verleysen.
* "Nonlinear   Dimensionality   Reduction", particularmente útil para entender as bases matemáticas necessárias.
* Para  "Fatoração  de  Matrizes  Não-Negativas",  o  texto  de Kim  Falk,  "Practical Recommender Systems", oferece uma explanação prática da implementação dessa técnica  em  sistemas  de  recomendação. 
*  "Recommender  Systems:  The  Textbook", Charu  C.  Aggarwal.
* "Practical  Recommender  Systems"  de  Kim  Falk  
